name: Build and Analyze Application

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  build_and_analyze_application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: Build Iact-Check-Webapp
        run: |
          cd iact-check-webapp/src/main/resources/webapp
          npm install -g @angular/cli
          npm install
          ng build --prod
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set Version
        run: mvn versions:set -DnewVersion=nightly#$(git rev-parse --short "$GITHUB_SHA")
      - name: Build and Test with Maven
        run: mvn -B clean verify
      - name: Rename Jars
        run: |
          mv iact-check-core/target/iact-check-core*.jar iact-check-core/target/iact-check-core.jar
          mv iact-check-webapp/target/iact-check-webapp*.jar iact-check-webapp/target/iact-check-webapp.jar
      - uses: actions/upload-artifact@master
        with:
          name: iact-check-core
          path: iact-check-core/target/iact-check-core.jar
      - uses: actions/upload-artifact@master
        with:
          name: iact-check-webapp
          path: iact-check-webapp/target/iact-check-webapp.jar
  build_docker_images:
    needs: build_and_analyze_application
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: iact-check-core
          path: iact-check-core/target/iact-check-core.jar
      - uses: actions/download-artifact@master
        with:
          name: iact-check-webapp
          path: iact-check-webapp/target/iact-check-webapp.jar
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Iact-Check-Core
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./iact-check-core/Dockerfile
          push: true
          tags: mortimercold/iact-check-core:nightly
      - name: Build and push Iact-Check-Webapp
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./iact-check-webapp/Dockerfile
          push: true
          tags: mortimercold/iact-check-webapp:nightly
