name: Build and Analyze Core

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  Build and Analyze Core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: Build Iact-Check-Webapp
        run: |
          cd iact-check-webapp/src/main/resources/webapp
          npm install -g @angular/cli
          npm install
          ng build --prod
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and Test with Maven
        run: mvn -B clean verify
      - name: Run Sonar Analysis on Core
        run: mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=solec0der_iact-check -Dsonar.organization=solec0der
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
