name: Deploy

# Controls when the action will run. 
on:
  create:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: Build Iact-Check-Webapp
        run: |
          cd iact-check-webapp/src/main/resources/webapp
          npm install -g @angular/cli
          npm install
          ng build --prod
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and Test with Maven
        run: mvn -B clean verify -DskipTests
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Iact-Check-Core.jar
        id: upload-iact-check-core
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./iact-check-core/target/${{ iact-check-core-${{ steps.get_version.outputs.VERSION }}.jar }}
          asset_name: iact-check-core-${{ steps.get_version.outputs.VERSION }}.jar
          asset_content_type: application/java-archive
