name: Create Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
        - name: Build Iact-Check-Webapp
          run: |
            cd iact-check-webapp/src/main/resources/webapp
            npm install -g @angular/cli
            npm install
            ng build --prod
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Set Version
          run: mvn versions:set -DnewVersion=$GIT_TAG_NAME
        - name: Build and Test with Maven
          run: mvn -B clean verify
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Build and push Iact-Check-Core
          run: |
            cd iact-check-core
            docker build -t mortimercold/iact-check-core:$GIT_TAG_NAME .
            docker push mortimercold/iact-check-core:$GIT_TAG_NAME
        - name: Build and push Iact-Check-Webapp
          run: |
            cd iact-check-webapp
            docker build -t mortimercold/iact-check-webapp:$GIT_TAG_NAME .
            docker push mortimercold/iact-check-webapp:$GIT_TAG_NAME
        - name: Commit Version
            run: |
              git config --global user.name 'Github'
              git config --global user.email 'yannick.huggler@users.noreply.github.com'
              git commit -am "Set version to $GIT_TAG_NAME"
              git push
